spring:
  application:
    name: Community


app:
  userFile: ./data/userdata.json
  userLikeFile: ./data/userlikedata.json
  postFile: ./data/postdata.json
  postEditFile: ./data/posteditrecorddata.json
  temporaryPostFile: ./data/temporarypostdata.json
  commentFile: ./data/commentdata.json
  refreshTokenFile: ./data/refreshtoken.json

tokenExpire:
  refresh: 1000*60*30
  access: 1000*60*10