spring:
  application:
    name: Community
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jwt:
    secret: ${JWT_SECRET}

server:
  forward-headers-strategy: framework

aws:
  s3:
    bucket: community-925581110470-ap-northeast-2-an
    region: ap-northeast-2

tokenExpire:
  refresh: 1800000
  access: 600000

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.web.method.annotation: TRACE
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: TRACE
    org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: DEBUG
    org.springframework.web.bind: DEBUG
    org.springframework.validation: DEBUG
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE