name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  build-and-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: CI 성공한 빌드 결과물 다운로드
        uses: actions/download-artifact@v5
        with:
          name: build-results
          path: build/libs
          run-id: ${{github.event.workflow_run.id}}
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: 다운로드 결과 확인
        run: |
          echo "현재 위치: $(pwd)"
          echo "build/libs 내부:"
          find build/libs -maxdepth 5 -type f -printf '%p\n'
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 이미지 빌드 및 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/community-be:${{ github.event.workflow_run.head_sha }}
            ${{ secrets.DOCKER_USERNAME }}/community-be:latest
          labels: |
            org.opencontainers.image.revision=${{ github.event.workflow_run.head_sha }}
  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: SSH Key 준비
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: 도커 설치 확인
        id: check-docker
        run: |
          DOCKER_EXISTS=$(ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'command -v docker >/dev/null && echo "true" || echo "false"')
          echo "docker_exists=$DOCKER_EXISTS" >> $GITHUB_OUTPUT
      - name: EC2에 도커 설치
        if: steps.check-docker.outputs.docker_exists == 'false'
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: bash scripts/ec2docker.sh
      - name: Deploy to EC2 via Docker Compose
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          BACKEND_IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        run: bash scripts/deploy.sh
